[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery = "EVBDA9Xjq37LdSwxj5s3txybtBAXNuveP8EGsisP2D25"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
